name: CaliforniaHousingRetraining
conda_env: conda.yaml
entry_points:
  main:
    command: "python modelling.py"
    parameters:
      random_state: {type: int, default: 42}
      n_estimators: {type: int, default: 100}